# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js base image
FROM node:20-alpine as build

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the application files
COPY . .

# Build the application
RUN npm run build

# Use a smaller Node.js base image for the final image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy the build artifacts from the previous stage
COPY --from=build /app/build ./build
COPY --from=build /app/package*.json ./
COPY --from=build /app/wrangler.jsonc ./

# Install only production dependencies
RUN npm install --omit=dev

# Expose port for worker binding
EXPOSE 8787

# Environment variables for container binding
ENV PORT=8787

# Define the command to run the Cloudflare Worker
# Using wrangler dev for local development or wrangler deploy for production
ENTRYPOINT ["npx", "wrangler", "dev", "--port", "8787", "--local"]
